### ISSUE TITLE
hello, it can support .net core well?why constructor arguments always null?

### ISSUE THREAD

**Issue by yunduansing** [pamidur/aspect-injector#100]
hello, it can support .net core well?why constructor arguments always null?

**Comment by pamidur** [comment]
Hi, 
Yes, it was developed .net core first. Could you please show a sample where it works unexpected way?

**Comment by yunduansing** [comment]
Yes,here are my code,just like youre sample code
    [Injection(typeof(CacheAspect))]
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Class)]
    public class CacheAttribute : Attribute
    {
        public string Key { get; set; }
        public bool Delete { get; set; }
        public CacheAttribute(string key,bool delete)
        {
            this.Key = key;
            this.Delete = delete;
        }
    }

**Comment by yunduansing** [comment]
sorry,its my fault,it can work
