### ISSUE TITLE
Pass Generic Type And OnException

### ISSUE THREAD

**Issue by murseld** [pamidur/aspect-injector#112]
Hi pamir
I know you hate me :) But
I am using this library for caching and  logging and its perfect going on memory cache with help you. but i want to use redis for cache and when i use it on method  i can not convert cache data on redis to method return data. 
do you have an idea?
and how can i catch exception message when happened any exception on method?

Thanks

`[CacheAspect(typeof(RedisCacheManager),5)]
        public List<User> GetList(Expression<Func<User, bool>> filter=null)
        {
            return  _userDal.GetList(filter);
        }`

`
namespace Rms.Core.Aspects.AspectInjector.CacheAspect
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    [Injection(typeof(CacheAspectFactory))]
    public class CacheAspect : Attribute
    {
        public CacheAspect(Type cacheType, int cacheByMinute)
        {
            CacheType = cacheType;
            CacheByMinute = cacheByMinute;
        }
        public Type CacheType { get; }
        public int CacheByMinute { get; }
    }

    [Aspect(Scope.Global)]
    public class CacheAspectFactory : Attribute
    {
        private readonly ConcurrentDictionary<Type, ICacheManager> _cacheManagers
            = new ConcurrentDictionary<Type, ICacheManager>();

        [Advice(Kind.Around, Targets = Target.Method)]
        public object OnInvoke(
            [Argument(Source.Metadata)] MethodBase metadata,
            [Argument(Source.Arguments)] object[] arguments,
            [Argument(Source.Instance)] object target,
            [Argument(Source.Target)] Func<object[], object> method,
            [Argument(Source.Triggers)] Attribute[] triggers
            )
        {
            var cacheTriggers = triggers.OfType<CacheAspect>().ToArray();

            if (cacheTriggers.Length != 0)
            {
                var methodName = $"{metadata.ReflectedType?.Namespace}.{metadata.ReflectedType?.Name}.{metadata.Name}";
                var key = $"{methodName}({string.Join(",", arguments.Select(x => x != null ? x.ToString() : "<Null>"))})";

                // method might be cached in different caches (memory, file, redis) with different settings at the same time
                foreach (var trigger in cacheTriggers)
                {
                    var cache = GetCacheManager(trigger.CacheType);
                    if (cache.IsAdd(key))
                    {
                      
                        var data = cache.Get<object>(key); //I cannot convert to method return type
                        return data; //trigger.CacheType;
                    }
                }
                var result = method(arguments);
                return result;
            }
            //this executes in unlikely case when this aspect is triggered not by Cache attribute, but something else
            return method(arguments);
        }

        [Advice(Kind.After, Targets = Target.Method)]
        public void OnExit(
            [Argument(Source.Type)] Type type,
            [Argument(Source.ReturnValue)] object retVal,
            [Argument(Source.Metadata)] MethodBase metadata,
            [Argument(Source.Arguments)] object[] arguments,
            [Argument(Source.Instance)] object target,
            [Argument(Source.Triggers)] Attribute[] triggers
        )
        {
            var cacheTriggers = triggers.OfType<CacheAspect>().ToArray();
            if (cacheTriggers.Length != 0)
            {
                var methodName = $"{metadata.ReflectedType?.Namespace}.{metadata.ReflectedType?.Name}.{metadata.Name}";
                var key =
                    $"{methodName}({string.Join(",", arguments.Select(x => x != null ? x.ToString() : "<Null>"))})";
                //add result to every cache
                foreach (var trigger in cacheTriggers)
                {
                    GetCacheManager(trigger.CacheType).Add(key, retVal, trigger.CacheByMinute);
                    Console.WriteLine($"Storred in {trigger.CacheType.Name} for {trigger.CacheByMinute} min");
                }
            }
        }

        public ICacheManager GetCacheManager(Type cacheType)
        {
            if (typeof(ICacheManager).IsAssignableFrom(cacheType) == false)
                throw new NullReferenceException("Wrong Cache Manager");
            return _cacheManagers.GetOrAdd(cacheType, t => (ICacheManager)Activator.CreateInstance(t));
        }

    }

}`

**Comment by pamidur** [comment]
I absolutely not hate you :)

From your code I don't understand why you added OnExit advice which does the same as OnInvoke ?
Second question is what is ```cache.Get<>()``` method ? Is there method where you could supply the Type? like ```cache.Get<object>(string key, Type returnType)``` ?

if not you could create needed methodRef call like this:
```c#
//add at the top of your aspect
 private readonly MethodInfo _getGeneric = typeof(ICacheManager).GetMethod(nameof(ICacheManager.Get));

//add argument to your OnInvoke method
[Argument(Source.ReturnType)] Type type

//get the data from cache like this:
var method = _getGeneric.MakeGenericMethod(type);
var data = method.Invoke(cache, key);

```

**Comment by pamidur** [comment]
If it doesn't work for you, drop me your ICacheManager class

**Comment by murseld** [comment]
Hi Pamidur.
Thanks for help again and it is working exactly like I want..
now your first  question i am using OnExit because that write data to cache when method is complete  if there is no data from cache. Second question cache.Get<> is a method on CacheManager that i was added to attach.
So i ask top but i guess you dont see that. How can i  catch exception from aspect when method throw any exception for log aspect. do you think that add new Kind for Advice like Kind.Exception..

Thanks for help again...
[CacheAspect.txt](https://github.com/pamidur/aspect-injector/files/3691019/CacheAspect.txt)
[CacheRemoveAspect.txt](https://github.com/pamidur/aspect-injector/files/3691020/CacheRemoveAspect.txt)
[ICacheManager.txt](https://github.com/pamidur/aspect-injector/files/3691021/ICacheManager.txt)
[LogAspect.txt](https://github.com/pamidur/aspect-injector/files/3691022/LogAspect.txt)
[RedisCacheManager.txt](https://github.com/pamidur/aspect-injector/files/3691023/RedisCacheManager.txt)

**Comment by pamidur** [comment]
well in your case the best solution would be one I suggested.

As for catching errors, I'd recommend to create new aspect for this specific purpose. If you want to catch exceptions in this aspect when calling original method, you do as usual:

```c#
try{
var result = method(arguments);
}
catch(Exception e){
//you need to decide what to do with it
}

```

**Comment by murseld** [comment]
Hi Pamidur
I am grateful for your help
Thanks...

**Comment by pamidur** [comment]
You are welcome! 
Feel free to reopen if needed
