### ISSUE TITLE
Build is failed if project has COM reference

### ISSUE THREAD

**Issue by 777AvEnGeR777** [pamidur/aspect-injector#131]
I have a project that references NetFwTypeLib COM reference.

When I try to build the project, AspectInjector failes with the following error:
"Reference not found: 'obj\Debug\Interop.NetFwTypeLib.dll'. Please submit an issue to https://github.com/pamidur/aspect-injector"

The dll exists in obj\Debug folder. If I will remove the reference, the project will be built successfully.

I've also tried to reference another COM libraries like Accessibility and NetCon1.0 Type Library, and they give the same result

**Comment by pamidur** [comment]
Thanks for report!
I'll take a look shortly

**Comment by pamidur** [comment]
should be fixed in 2.4.1
