### ISSUE TITLE
A naming conflict with Serilog.Log if name the attribute as Log

### ISSUE THREAD

**Issue by KKacer** [pamidur/aspect-injector#135]
I have this code:

    [Aspect(Scope.Global)]
    [Injection(typeof(LogCall))]
    public class LogCall : Attribute
```
    {
        [Advice(Kind.Around, Targets = Target.Method)]
        public object HandleMethod(
            [Argument(Source.Name)] string name,
            [Argument(Source.Arguments)] object[] arguments,
            [Argument(Source.Target)] Func<object[], object> method)
        {
            Log.Information("Something");
...
```

As the `Log.Information` is part of **Serilog**, it will conflict if I want to make the attribute named **Log** not **LogCall**, though I prefer to name it as **Log**.
Do you know a simple way to be able to name that attribute just **[Log]**?

Regards.

**Comment by pamidur** [comment]
Yes, remove Serilog from usings at the top of the file, and use full namespace in place, like:
```c#
Serilog.Log.Information("Something");
```

**Comment by KKacer** [comment]
Aha! :D right, forgot that could use it this way.

**Comment by KKacer** [comment]
Changed that but found that it will conflict with all the logs inside all the libraries, if the name was LogAttribute it could prevent that. but currently I decided to use another name instead of Log to prevent the need to change all the Log.Somethings in the codes.

**Comment by pamidur** [comment]
Why not rename it to LogAttribute or LogCallAttribute?

**Comment by KKacer** [comment]
Still didn't try LogAttribute which guess will work, at first thought maybe it is not possible via your code or you don't suggest that, cause you didn't use 'Attribute' in the names, guessed may cause some troubles in your library, e.g if you were trimming names, ...

Update: yes, attribute fixed the issue with naming conflicts.

**Comment by pamidur** [comment]
@KKacer it is just personal preference - not to use ...Attribute suffix.
As for AspectInjector - it is designed in a way _"if it compiles - it is valid code for AspectInjector"_

**Comment by KKacer** [comment]
Yes got it, said that just to clarify why I worried and avoided using 'Attribute' at first, but as you said it worked. All fine, thanks.
