### ISSUE TITLE
Consider also shipping a fody addin?

### ISSUE THREAD

**Issue by SimonCropp** [pamidur/aspect-injector#14]
Looks like this would work well as a fody weaver https://github.com/Fody/Fody

Would you consider also shipping the functionality as a fody extension?

**Comment by pamidur** [comment]
I don't see the way it can be done. These projects are somewhat opposite. Fody extends assembly via imperative code while AspectInjector does via declarative attributes. AspectInjector allows to debug aspects while Fody does not.

**Comment by pamidur** [comment]
When you have any idea about the way it can be done - reopen this issue please.
