### ISSUE TITLE
Caching doesn't work with scoped DI instances

### ISSUE THREAD

**Issue by MaciejWanat** [pamidur/aspect-injector#144]
I've been recently looking for a library for simple, effective caching using attributes, and your library with `cache` extension does pretty much exactly what I've been looking for.

The problem I've encountered is that I've used it with pretty standard ASP.NET application, with multiple sercives registered as `scoped`. In this quite standard scenario caching doesn't work, because `cache key` in your implementation is created basing on instance - and the instance is different with each request (https://github.com/pamidur/aspect-injector/blob/master/samples/src/Cache/CacheAspect.cs#L83).

Would you consider addresing that problem? The solution I've used is to simply base on method name + arguments as a key. I had to adjust it for my project myself, so I could give a PR for you if you accept external PRs.

**Comment by pamidur** [comment]
Hi @MaciejWanat , your suggestion does sound good! What about using type instead of instance? it'll have about the same entropy but will still work with different instances.
I'd happily accept your PR!

Thank you for your interest in this project

**Comment by MaciejWanat** [comment]
Great! I will prepare a PR soon.

**Comment by pamidur** [comment]
I was thinking we could ither move key calculation to attribute or just add additional parameter to indicate if cache should be per instance:

```c#
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class MemoryCacheAttribute : CacheAttribute
    {
        private static readonly MemoryCache _cache = new MemoryCache("aspect_builtin_memory_cache");
        private readonly uint _seconds;
        
        public bool PerIntsanceCache {get;set;} = true;


        public MemoryCacheAttribute(uint seconds)
        {
            _seconds = seconds;
        }

        public override ObjectCache Cache => _cache;
        public override CacheItemPolicy Policy => new CacheItemPolicy() { AbsoluteExpiration = DateTimeOffset.UtcNow.AddSeconds(_seconds) };
    }

//the use it like this
[MemoryCache(3000, PerIntsanceCache = false)]
```

Other option is to move key calculation to the attribute:
```c#
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true, Inherited = true)]
    [Injection(typeof(CacheAspect), Inherited = true)]
    public abstract class CacheAttribute : Attribute
    {
        public abstract ObjectCache Cache { get; }

        public abstract CacheItemPolicy Policy { get; }

        public virtual GetKey(type, instance, method, args) { .. }
    }
```

**Comment by MaciejWanat** [comment]
This failed test is passing when ran directly, doesn't when tests are run altogether.
