### ISSUE TITLE
Not working with Visual Studio

### ISSUE THREAD

**Issue by kalarani** [pamidur/aspect-injector#15]
The aspect injector does not kick in when i build from VisualStudio. It works when I run msbuild from command line. I see the following statements in console.

"Assembly has been loaded"
"Assembly has been patched"
"Assembly has been written"

But, when i build it from VS, I don't see these lines and the aspect injector attribute doesn't work. Am i missing something here?

**Comment by pamidur** [comment]
Sorry for delay. What version of VS you use?

**Comment by kalarani** [comment]
It is VS Ultimate 2013

**Comment by pamidur** [comment]
Could you please share code (solution, csproj, cs)?

**Comment by kalarani** [comment]
Hi, this seems to be a glitch. It works now. Thanks!

**Comment by pamidur** [comment]
Thank you!
