### ISSUE TITLE
JetBrains dotCover fails to gather coverage of tests with aspects Kind.Around

### ISSUE THREAD

**Issue by sergeprozorov** [pamidur/aspect-injector#150]
Hello,

The issue might be related to #107, but the error message I see is different. Additionally, I provide a reliable way to reproduce it.
The scenario is following

Run the unit tests from AspectInjector.SampleApps with code coverage. You can see that code coverage report is empty.
![image](https://user-images.githubusercontent.com/14787310/112981006-e3ced800-915a-11eb-8a3d-d3d936e2cc2b.png)

If you run a test session without CacheTests with code coverage, you will see some results there.
![image](https://user-images.githubusercontent.com/14787310/112981227-2b556400-915b-11eb-8db8-de340262c7b9.png)

In order to see the error message itself being produced by dotCover, I have used the approach described [here](https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html#using-dotnet-exe-to-run-coverage-analysis-of-unit-tests), because it is the simplest for me. The message is following.
```shell
[JetBrains dotCover] Coverage session finished with errors: Jump to invalid address
[location] = C:\BuildAgent\work\82554ce5cfd8f0cd\Profiler\Kernel\Windows\Native\Solution\core\src\IL\InjectILMethod.MainPass.cpp(388)
[function] = unsigned int __cdecl InjectILMethod::Translate(unsigned int,bool)
[token] = 06000012, MethodDef
[method name] = CalculateTask
[module name] = C:\work\temp\aspect-injector\samples\tests\Aspests.Tests\bin\Debug\netcoreapp2.1\Aspests.Tests.dll
[type name] = Aspests.Tests.CacheTests+TestClass.
```
Additionally, I would like to mention that it is not only dotCover that fails to collect code coverage. One of my colleagues has also tried OpenCover with a similar result. It is pity but this issue is a blocker for us currently, as it breaks our CI workflow.

**Comment by pamidur** [comment]
ok, it seems that the dotCover modifies the assembly to gather the coverage results, which make sense.
The problem it seems that dotCover conflicts with AspectInjector somehow.

Thanks for reliable way get it

**Comment by sergeprozorov** [comment]
@pamidur Yes, the issue appears to be fixed. I have checked it on a couple of projects (on AspectInjector.SampleApps too). Code coverage works now in the both VS UI and dotCover CLI.
Thank you, great work!

**Comment by pamidur** [comment]
this 2.5.1-pre1 should be stable despite it is pre-release, So I guess you might safely use it until full release is out. Possible issues are only with debug process:
- breakpoints fire in wrong places
- watch/locals doesn't show (some) local scope variables

I have experienced none of above tho.
Please report if find any bugs))
