### ISSUE TITLE
Version 2.6.0-pre1 ?

### ISSUE THREAD

**Issue by StefH** [pamidur/aspect-injector#157]
Can you please tell us the difference / release notes for this this preview ?

**Comment by pamidur** [comment]
2.6.0 will bring updated type-lookup system. It should resolve issues like #138 and also ensure support for net5.0 and later.

Release notes are usually quite complete on Releases page so you can trust it

**Comment by pamidur** [comment]
https://github.com/pamidur/aspect-injector/releases

**Comment by pamidur** [comment]
I'll close this one, please feel free to reopen if needed!
