### ISSUE TITLE
how can return value with Task

### ISSUE THREAD

**Issue by ioer2008** [pamidur/aspect-injector#159]
var result = await ((Task<T>)target(args)).ConfigureAwait(false);
If you execute this sentence, you will report an error.

The official UniversalWrapper sample run exits directly, changes it to .net 5, and throws an exception "System.Exception".

Can you give an official example of using redis and task

**Comment by pamidur** [comment]
Hi @ioer2008 , Could you please provide some more context to the issue? The aspect code and target code (where you apply aspect) will help a lot!

**Comment by ioer2008** [comment]
Sorry, the code is uploaded to https://github.com/ioer2008/OrleansDemo.

in /Grains/RedisCacheAttribute.cs,the result value can't set to redis.

**Comment by pamidur** [comment]
I made a new version of Aspects.Cache so it should should work with your case:
```sh
dotnet add package Aspects.Cache --version 2.0.0
```

```c#
    public class RedisCacheAttribute : DistributedCacheBaseAttribute
    {
        private static readonly RedisCache _cache = new RedisCache(new OptionsWrapper<RedisCacheOptions>(new RedisCacheOptions
        {
            Configuration = "localhost:6379",
            InstanceName = "Example"
        }));

        public RedisCacheAttribute(uint seconds, bool perInstanceCache = false)
        {
            Policy = new DistributedCacheEntryOptions { AbsoluteExpiration = DateTimeOffset.UtcNow.AddSeconds(seconds) };
            PerInstanceCache = perInstanceCache;
        }

        public override IDistributedCache Cache => _cache;
        public override DistributedCacheEntryOptions Policy { get; }    
    }
```

**Comment by ioer2008** [comment]
Thank you very much for your modification, but I added the above code to the file and still reported an error. Maybe it doesn't support Orleans.

https://github.com/ioer2008/OrleansDemo

**Comment by pamidur** [comment]
Well I guess it doesn't directly support async methods, so if you want to cache one of them - additional development is required, you can refer here on how to do it https://github.com/pamidur/aspect-injector/tree/master/samples/src/Universal
