### ISSUE TITLE
AI FAIL. Aspect Injector processing has failed. See other errors

### ISSUE THREAD

**Issue by oleksandrp1** [pamidur/aspect-injector#167]
Hi,
After update Visual Studio from 2019 to 2022, installing .Net 6.0 and adapting the project to the new versions I get the error during a build: "AI FAIL. Aspect Injector processing has failed. See other errors". No other errors appear.
ApsectInjector 2.6.0.
What additional information do you need?

**Comment by oleksandrp1** [comment]
The issue is not reproducible. Close the ticket.

**Comment by pamidur** [comment]
Oh it was fast.
Thank you for report anyway!
