### ISSUE TITLE
Make TargetValue (former TargetReturnValue) contain oldvalue ( getter(); ) for InjectionTargets.Setter

### ISSUE THREAD

**Issue by deresh-andrew** [pamidur/aspect-injector#17]
This can be easily done via reflection, but it requires extra overhead for each new instance. As far as I understand, if this is done the same way as the others AdviceArgumentSource, there will be now overhead. For InjectionTargets.Getter return both Getter and Setter MethodInfo. Same for InjectionTargets. Add and InjectionTargets.EventRemove. 

Some use case: implement INotifyPropertyChanged and check if property is changed.
In the current version I cannot do anything better than(maybe there is a better way?):

```
		private bool _hasChanged;
		private MethodInfo _getter;

		[Advice(InjectionPoints.Before, InjectionTargets.Setter)]
		public void NotifyChangeBefore([AdviceArgument(AdviceArgumentSource.Instance)] object instance,
		                               [AdviceArgument(AdviceArgumentSource.TargetName)] string name,
		                               [AdviceArgument(AdviceArgumentSource.TargetArguments)] object[] parameters,
										[AdviceArgument(AdviceArgumentSource.AbortFlag)] ref bool abort)
		{
			if (_getter == null)
			{
				var t = instance.GetType();
				var p = t.GetProperties().Single(info => info.Name == name);

				_getter = p.GetGetMethod();
			}

			var oldValue = _getter.Invoke(instance, null);
			var newValue = parameters.Single();

			_hasChanged = !Equals(oldValue, newValue);
			if (!_hasChanged)
				abort = true;
		}
```

**Comment by pamidur** [comment]
I got the idea. Need to think how it can be done.

**Comment by pamidur** [comment]
Agreed to rename TargetReturnValue to TargetValue and use it for old value on setter. Scope changed to 1.0

**Comment by pamidur** [comment]
Release in 0.9.4
