### ISSUE TITLE
Feature: Does attribute can work with Ioc like Autofac

### ISSUE THREAD

**Issue by nepton** [pamidur/aspect-injector#181]
Can you support the attribute ( like LogAttribute etc ) can create from the Ioc framework, or create by a factory that I can control it.
Thanks.

**Comment by pamidur** [comment]
Hi @nepton , sorry for delay. You can already use with IoCs, see here #166

**Comment by nepton** [comment]
thanks

**Comment by pamidur** [comment]
Please feel free to reopen if needed
