### ISSUE TITLE
Visual Studio 2015 - AspectInjector - PdbDebugException issue

### ISSUE THREAD

**Issue by suresh-s** [pamidur/aspect-injector#19]
We are using AspectInjector Version 0.9.41 in our portal class library (Targets .NET Framework 4.5+ Windows 8 + Windows Phone 8.1 + Windows Phone Silverlight 8) and Windows phone 8.0 Silverlight app.

Visual Studio 2013 compiles the Solution without any build error.

Visual Studio 2015 compiles the Solution with following errors with Stacktrace

Error PdbDebugException: Unknown custom metadata item kind: 7 at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits) at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits) at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings) at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary2 nameIndex, PdbReader reader) at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary2& tokenToSourceMapping, String& sourceServerData) at Mono.Cecil.Pdb.PdbReader.PopulateFunctions() at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header) at Mono.Cecil.ModuleDefinition.ProcessDebugHeader() at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader) at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters) at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters) at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()

Error PdbDebugException: Unknown custom metadata item kind: 6 at Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits) at Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits) at Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean readStrings) at Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, IntHashTable names, ArrayList funcList, Boolean readStrings, MsfDirectory dir, Dictionary2 nameIndex, PdbReader reader) at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary2& tokenToSourceMapping, String& sourceServerData) at Mono.Cecil.Pdb.PdbReader.PopulateFunctions() at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header) at Mono.Cecil.ModuleDefinition.ProcessDebugHeader() at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader) at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters) at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters) at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) at AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()

Please fix this issue.

**Comment by pamidur** [comment]
Thank you for the report. Will take a look asap

**Comment by pamidur** [comment]
fixed in 0.9.42

**Comment by suresh-s** [comment]
Thank you,  I have tested 0.9.42.  It is working fine now in VS2015

**Comment by pamidur** [comment]
good to know, thank you!

**Comment by suresh-s** [comment]
Before we used AspectInjector 0.9.31 version, it hase Enum value AdviceArgumentSource.TargetReturnValue, Version 0.9.42 doesn't have TargetReturnValue.  It has only TargetValue.  Could we use AdviceArgumentSource.TargetValue instead of AdviceArgumentSource.TargetReturnValue? Both are same?

**Comment by YuriyIvon** [comment]
We renamed TargetReturnValue to TargetValue while implementing solution to the issue #17. So yes, please use TargetValue, it will work correctly.
