### ISSUE TITLE
Feature: using Apects.Cache and other parent nugets without runnining aspect-injector every build

### ISSUE THREAD

**Issue by kondr1** [pamidur/aspect-injector#192]
I using Aspects.Cache in my nuget, but don't use ApsectInjector. So it running every build =(
```
AspectInjector|1.0.0: Found 0 aspects, 0 injections
```
In my main solution i plan don't use any injections too
I need to use `<AspectInjector_Enabled>false</AspectInjector_Enabled>` in every csproj? Maybe exists some workaround?

**Comment by pamidur** [comment]
Let me reiterate and see if I got your issue right:

- You have assembly A with which you use AspectInjector
- You have assemblies B,C,D which reference assm A
- You want to limit AspectInjector compiler only to assm A

If that's the case - you can make all references resources in assm  A - **Private** as per https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets.
```xml
<ItemGroup>
    <PackageReference Include="AspectInjector" Version="2.7.3" PrivateAssets="all" />
  </ItemGroup>
```

**Comment by kondr1** [comment]
In that case i need `PrivateAssets="all"` in [that file](https://github.com/pamidur/aspect-injector/blob/master/samples/Directory.Build.props#L14)

**Comment by pamidur** [comment]
Oh my bad actually, you'll need either
```xml
  <ItemGroup>
    <PackageReference Include="Aspects.Cache" Version="2.0.2" PrivateAssets="buildTransitive"/>
  </ItemGroup>
```
or  this if you want to completely hide caching attributes and classes
  ```xml
  <ItemGroup>
    <PackageReference Include="Aspects.Cache" Version="2.0.2" PrivateAssets="all"/>
  </ItemGroup>
```

**Comment by pamidur** [comment]
Please feel free to reopen this issue if it doesn't work for you!
