### ISSUE TITLE
Support Async Methods as Target

### ISSUE THREAD

**Issue by pamidur** [pamidur/aspect-injector#2]

**Comment by pamidur** [comment]
@YuriyIvon put here those links on how ilspy guys did that, pls

**Comment by YuriyIvon** [comment]
Here it is: http://community.sharpdevelop.net/blogs/danielgrunwald/archive/2012/04/16/decompiling-async-await.aspx

**Comment by pamidur** [comment]
done in 1.0.0-beta1
