### ISSUE TITLE
Aspects not work with static members

### ISSUE THREAD

**Issue by kazachis4e** [pamidur/aspect-injector#20]
I trying to mark my static methods by aspect - its not work. On non-static members its work fine. Its bug or i something missing?

**Comment by pamidur** [comment]
Thank you for the report. Could you please provide sample code?

**Comment by kazachis4e** [comment]
public class MyAspect
    {
        [Advice(InjectionPoints.Before, InjectionTargets.Method)]
        public void AspectMethodRealization()
        {
            Console.WriteLine("Aspect Works!!!");
        }
    }

[Aspect(typeof(MyAspect))]
    public static class MyStatic
    {
        public static void StaticTest()
        {
            Console.WriteLine("Static Test");
        }
    }

class Program
    {
        static void Main(string[] args)
        {
            MyStatic.StaticTest();
        }
    }

Output is only "Static Test".

**Comment by pamidur** [comment]
fixed in 0.9.43
