### ISSUE TITLE
Aspect Injector processing has failed (v2.8.0),  Mono.Cecil.Cil.SymbolsNotFoundException

### ISSUE THREAD

**Issue by minchili** [pamidur/aspect-injector#200]
Environment (please complete the following information):

OS: Windows 10 64 bit
Framework: .Net Framework 4.7.2, C# 8.0
Type of application: dll / Console
Version of AspectInjector: 2.8.0

Describe the bug

When I create the project and install Aspect Injector and then build I get the following error:
(The project has not even written any code, it is just a simple build.)

Error1: Aspect Injector processing has failed. See other errors.
Error2: Processing failure: Mono.Cecil.Cil.SymbolsNotFoundException: No symbol found for file: C:\Users\*****\*****\Repositories\Samples\AOP\ClassLibrary1\obj\Debug\ClassLibrary1.dll

**Comment by pamidur** [comment]
Hi @minchili , thank you for the report, I'll look at it shortly.
Is there any chance you could send the project as zip?

**Comment by minchili** [comment]
[ClassLibrary1.zip](https://github.com/pamidur/aspect-injector/files/9938279/ClassLibrary1.zip)
Thanks for the reply, here is the project where the error occurred.

**Comment by pamidur** [comment]
What  IDE  you use? I didn't manage  to reproduce it on VS2022

**Comment by minchili** [comment]
I use VS2022 too, this is my IDE info.
[IDE Info.txt](https://github.com/pamidur/aspect-injector/files/9965995/IDE.Info.txt)

**Comment by leandrogomes777** [comment]
Hi, we've have the same issue here.

We have a workaround to compile.
Set the DebugType on your csproj to portable (instead of full or pdbonly).
Ex:
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    **<DebugType>portable</DebugType>**

@pamidur could you address this issue? We have to maintain the configuration of pdb to "full" here.

**Comment by pamidur** [comment]
@leandrogomes777 thank you for the input. It is definitely an issue with PDB type and Mono.Cecil

**Comment by pamidur** [comment]
@leandrogomes777 @minchili 
could you please check if 2.7.2 and 2.7.1 have the same issue?

**Comment by leandrogomes777** [comment]
Hi @pamidur, i've made tests with the 2.7.2 version and no issues.
