### ISSUE TITLE
Feature: Why `GetInstance` method for Factory should be static?

### ISSUE THREAD

**Issue by IbrahimElshafey** [pamidur/aspect-injector#216]
Why not something similar to [JobActivator ](https://docs.hangfire.io/en/latest/background-methods/using-ioc-containers.html)? to enable easy use.

**Comment by pamidur** [comment]
It took me some time to understand. The reason is that Aspect Injectior might not be able to instantiate the factory class. 
Inside static GetInstance method you may hook it to any DI you like though

**Comment by pamidur** [comment]
In future I plan for better DI frameworks support. 
For now I'll close the issue, but feel free to reopen if needed
