### ISSUE TITLE
Add AbortFlag to Exception InjectionPoint

### ISSUE THREAD

**Issue by Albeoris** [pamidur/aspect-injector#24]
It should be possible to suppress the exception after handling.

```C#
        [Advice(InjectionPoints.Before, InjectionTargets.Method)]
        public void HandleException(
            [Arg(Source.Instance)] Object owner,
            [Arg(Source.TargetException)] Exception targetException)
        {
            UiHelper.ShowError((FrameworkElement)owner, targetException);
            //TODO: don't throw the exception
        }
```

**Comment by YuriyIvon** [comment]
We are working on a new feature of Aspect Injector - InjectionPoints.Around, which will give more flexibility for wrapping existing methods. The idea is that your advice method will accept a parameter with a delegate to original method, and body of the original target method will be "replaced" with the body of your advice method. In you particular example you'll be able to wrap a call to original method with try/catch. We expect that with introduction of this feature Exception injection point and abort flag will be no longer needed.

**Comment by Albeoris** [comment]
Sounds great! When can I touch it?

**Comment by pamidur** [comment]
I'm in the process of moving to another city at the moment. So my guess would be in few weeks.

**Comment by pamidur** [comment]
I'm working on Around Injection now

**Comment by Albeoris** [comment]
Do you have any news?

**Comment by pamidur** [comment]
I'm working on it now. But unfortunately I can't provide you with ETA.
