### ISSUE TITLE
AdviceArgumentSource.TargetArguments not working in static methods

### ISSUE THREAD

**Issue by pairbit** [pamidur/aspect-injector#25]
![Error](https://cloud.githubusercontent.com/assets/1288091/12583050/cc3b9a7e-c451-11e5-99f7-4f2d1537e9a2.png)

![Resolve](https://cloud.githubusercontent.com/assets/1288091/12582993/6e36516c-c451-11e5-95a9-45097a3fc1d6.png)

**Comment by pamidur** [comment]
Thank you! I'll fix that in async branch and than merge it to master.

**Comment by pamidur** [comment]
done in async branch
