### ISSUE TITLE
Fix boxing unboxing result for Around reafure

### ISSUE THREAD

**Issue by pairbit** [pamidur/aspect-injector#26]
![Error](https://cloud.githubusercontent.com/assets/1288091/12613917/ba8e14fc-c50d-11e5-8f81-bd0900c1130f.png)

![Resolve](https://cloud.githubusercontent.com/assets/1288091/12614039/74aa68a4-c50e-11e5-81aa-55b75dc501d2.png)

**Comment by pamidur** [comment]
Thanks. I'll take care of it
