### ISSUE TITLE
Add ordering possibilities

### ISSUE THREAD

**Issue by pamidur** [pamidur/aspect-injector#29]
The fact is compiler doesn't necessary have to put attributes into an assembly in order they are stated in the code.
The issue is there. Especially in release configuration.

We might introduce Order parameter into AspectAttribute. Don't know what to do with custom attributes though. What is your opinion?

**Comment by forcewake** [comment]
Dear @pamidur 
I think that it will be nice to have this feature.
Imagine that you have created Feature Toggle system which is based on AOP.
You will use several custom attributes on one method or even class - so the order of the attributes will be helpful as for me. It will make possible to turn on or turn off some functionality based on current system's state.

**Comment by pamidur** [comment]
done in 2.0.0-beta1
