### ISSUE TITLE
Support Code-Contracts

### ISSUE THREAD

**Issue by pamidur** [pamidur/aspect-injector#3]
Since AI modifies assembly before Code contracts, we have to inject code after code contracts notions

**Comment by antbann** [comment]
Would you please comment on status of this issue - are there plans of fixing this? We've faced with it in our project. Thanks in advance for responce!

**Comment by pamidur** [comment]
We didn't know if there was any project uses both code contracts and aspectinjector :)

You've just escalated its importance. Will take a look in a few days.
________________________________
Від: antbann<mailto:notifications@github.com>
Надіслано: ‎12.‎08.‎2015 15:49
Кому: pamidur/aspect-injector<mailto:aspect-injector@noreply.github.com>
Копія: Alexander Guly<mailto:agulyj@live.com>
Тема: Re: [aspect-injector] Support Code-Contracts (#3)

Would you please comment on status of this issue - are there plans of fixing this? We've faced with it in our project. Thanks in advance for responce!

---

**Comment by pamidur** [comment]
Isn't going to happen
