### ISSUE TITLE
Remove information about the aspect-injector from stack trace

### ISSUE THREAD

**Issue by forcewake** [pamidur/aspect-injector#30]
For example PostSharp itself does not add the stack trace - it is very helpful during reading logs from the application.

But aspect-injector doesn't hide this unnecessary information, I mean:
![image](https://cloud.githubusercontent.com/assets/1325702/12785307/f79b31ce-ca9c-11e5-86d0-52a0a9c1cdf8.png)

**Comment by pamidur** [comment]
We can definitely hide it from debug session, though I'm not quite sure it is possible with stacktrace without direct modification of it.
Will sacrifice performance for cleaner stacktrace?

**Comment by pairbit** [comment]
You must take into account that the methods will not work properly with InjectionPoints.Around:

1. MethodBase.GetCurrentMethod
2. Assembly.GetCallingAssembly
3. new StackTrace()

Source ClassLibrary1:
```csharp
public class Lib
{
	private static readonly Func<MethodBase> CurrentMethod = MethodBase.GetCurrentMethod;
	private static readonly Func<Assembly> CallingAssembly = Assembly.GetCallingAssembly;

	public static void Test1()
	{
		Log(CurrentMethod(), CallingAssembly(), new StackTrace());
	}

	[Aspect(typeof(TestAspect))]
	public static void Test2()
	{
		Log(CurrentMethod(), CallingAssembly(), new StackTrace());
	}

	static void Log(MethodBase method, Assembly assembly, StackTrace stackTrace)
	{
		Console.WriteLine("CurrentMethod: {0}", method.Name);
		Console.WriteLine("CallingAssembly: {0}", assembly.GetName().Name);
		Console.WriteLine("StackTrace {0}:", stackTrace.FrameCount.ToString());
		foreach (var frame in stackTrace.GetFrames())
		{
			var frameMethod = frame.GetMethod();
			Console.WriteLine("{0}.{1}", frameMethod.DeclaringType.Name, frameMethod.Name);
		}
		Console.WriteLine();
	}
}

class TestAspect
{
	[Advice(InjectionPoints.Around, InjectionTargets.Method)]
	public Object Test(
		[AdviceArgument(AdviceArgumentSource.Arguments)] Object[] args,
		[AdviceArgument(AdviceArgumentSource.Target)] Func<Object[], Object> target)
	{
		return target(args);
	}
}
```
Source ConsoleApplication1:
```csharp
class Program
{
	static void Main(string[] args)
	{
		Lib.Test1();
		Lib.Test2();
	}
}
```
Result:
![2016-02-08_1652](https://cloud.githubusercontent.com/assets/1288091/12887304/755f50b4-ce84-11e5-8dd0-51e24308658d.png)

**Comment by pamidur** [comment]
done in 2.0.0-beta1
