### ISSUE TITLE
[BUG] Debugging is not working properly with InjectionPoints.Around

### ISSUE THREAD

**Issue by pairbit** [pamidur/aspect-injector#32]
Video:

1. [Incorrect order of method calls](http://screencast.com/t/eTgM6eILP)
2. [Doesn't break in breakpoint](http://screencast.com/t/U5WBgEDw)

**Comment by pamidur** [comment]
It is strange. It should be like that definitely.
Could you please upload compiled assembly somewhere? (dropbox?)
