### ISSUE TITLE
Static methods causes a runtime error

### ISSUE THREAD

**Issue by pberggreen** [pamidur/aspect-injector#36]
If I put an aspect on a static method I get the following runtime error when the method is called: 
"Common Language Runtime detected an invalid program"

I am using version 0.9.44

**Comment by YuriyIvon** [comment]
Please share the method signature and aspect definition

**Comment by pberggreen** [comment]
The following code uses the default TraceAspect.
It fails on the call to StaticTest() with a "Common Language Runtime detected an invalid program." exception. 
If you remove the Aspect attribute on StaticTest() it runs fine. 
The same thing happens if I put the Aspect attribute on the MainWindow class.

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        [Aspect(typeof(TraceAspect))]
        private void button_Click(object sender, RoutedEventArgs e)
        {
            StaticTest();
        }

        [Aspect(typeof(TraceAspect))]
        private static void StaticTest()
        {
        }
    }

    public class TraceAspect
    {
        private int count;

        [Advice(InjectionPoints.Before, InjectionTargets.Method)]
        public void CallCountTrace()
        {
            Console.WriteLine("Call #{0}", count);
            count++;
        }
    }

**Comment by YuriyIvon** [comment]
Thanks, I have managed to reproduce the issue - it occurs if the same aspect is applied both to static and non-static methods in the same class. We will start working on the fix.

**Comment by YuriyIvon** [comment]
I've pushed the fix, it will be available in the nearest release
