### ISSUE TITLE
Custom Attribute definition is failed outside assembly

### ISSUE THREAD

**Issue by Imjamshid** [pamidur/aspect-injector#37]
"AspectDefinition" is an internal class definition, then how could I get this class for creating custom Attribute in the "outside assembly"  ?

I used following test case for creating custom attribute.

https://github.com/pamidur/aspect-injector/blob/1.0.0-beta1/AspectInjector.Tests/CustomAttributes/CustomAttributesTests.cs

**Comment by pamidur** [comment]
AspectDefinitionAttribute is the class you are looking for

**Comment by Imjamshid** [comment]
Yes, I looking for "AspectDefinition" attribute. Let me know, what is the namespace..

**Comment by pamidur** [comment]
AspectInjector.Broker.AspectDefinitionAttribute

**Comment by pamidur** [comment]
Does it help?
