### ISSUE TITLE
Compilation issue when not providing a getter when injecting around a property setter

### ISSUE THREAD

**Issue by b4barnett** [pamidur/aspect-injector#47]
I have an aspect that is set up to inject before a property setter, I've found that I get the below compilation issue if I only provide a setter on the property. The compilation issue goes away when a getter is provided.

> AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error : NullReferenceException: Object reference not set to an instance of an object.
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Contexts.TargetMethodContext.get_MethodResultVariable()
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Injectors.AdviceInjector.InjectMethodCallWithResultReplacement(AdviceInjectionContext context, Instruction injectionPoint, Instruction returnPoint, FieldReference sourceMember)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Injectors.AdviceInjector.Inject(AdviceInjectionContext context)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Processors.AspectProcessors.AdviceProcessor.Process(AspectContext context)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessAspectDefinitions(MethodDefinition targetMethod, String targetName, IEnumerable`1 aspectDefinitions)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Processors.ModuleProcessors.InjectionProcessor.ProcessModule(ModuleDefinition module)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at AspectInjector.BuildTask.Processors.AssemblyProcessor.Process(AssemblyDefinition assembly)
AspectInjector.0.9.44\build\AspectInjector.targets(5,5): error :    at 
 AspectInjector.BuildTask.AspectInjectorBuildTask.Execute()

My aspect is set up like below
`		[Advice( InjectionPoints.Before, InjectionTargets.Setter )]
		public void BeforePropertySetterSecurityCheck( [AdviceArgument( AdviceArgumentSource.AbortFlag )] ref bool abortFlag,
										[AdviceArgument( AdviceArgumentSource.RoutableData )] object data,
										[AdviceArgument( AdviceArgumentSource.Instance )] object instance )`

and applied on the property like this

`		[UserRoleRequired( "Basic") ]
		public int SomeProperty
		{
			set
			{
			}
		}`

**Comment by YuriyIvon** [comment]
Could you try the same with the most recent pre-release version? I couldn't reproduce it with the most recent code. There were many changes since the last release, so it should be already fixed.

**Comment by b4barnett** [comment]
Yes error does not occur in pre-release,

Thanks
