### ISSUE TITLE
Net Core support

### ISSUE THREAD

**Issue by kongres** [pamidur/aspect-injector#48]
Hi.

I'm investigating your library. It looks like very flexible solution for AOP.

I've tried to use it in Net Core projects but it doesn't look to work. 

1) I just created empty console app based on Net Core.
2) Added your lib and changed Framework to 4.6.1 in project.json:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "AspectInjector": "1.0.0-beta4"
  },

  "frameworks": {
    "net461": {
    }
  }
}
```
3) Added test code:

```
using System;

namespace AspectInjectorTest
{
    using AspectInjector.Broker;

    public class Program
    {
        public static void Main(string[] args)
        {
            var container = new Container();

            container.Load();
            container.Load();
            container.Save();

            Console.ReadLine();
        }
    }


    [Aspect(typeof(TraceAspect))]
    public class Container
    {
        public string Name { get; set; }

        public void Load() { }
        public void Save() { }
    }

    public class TraceAspect
    {
        private int count;

        [Advice(InjectionPoints.Before, InjectionTargets.Method)]
        public void CallCountTrace()
        {
            Console.WriteLine("Call #{0}", count);
            count++;
        }
    }
}

```

It doesn't show any errors but in console is nothing. The same sample work in previous .Net.

Will you add support of .Net Core for this lib?

Regards.
Igor.

**Comment by YuriyIvon** [comment]
Thanks for the report, we will investigate the issue.

**Comment by pamidur** [comment]
Hello,
Since Microsoft announced they are going to abandon project.json and get back to (significantly modified) .csproj instead; we need to wait a little and see where they come. Until then I don't think it is possible to have bullet-proof support for .NETCore . However if anyone come up with a good workaround I'm all ears!

**Comment by pamidur** [comment]
Will be supported in future versions. But vs2017 is required.

**Comment by pamidur** [comment]
we support NetCore on vs2017 (new csproj) in https://github.com/pamidur/aspect-injector/releases/tag/1.0.0-rc1
