### ISSUE TITLE
Any news for .Net Core Project Compability?

### ISSUE THREAD

**Issue by drony** [pamidur/aspect-injector#66]
Any news for .Net Core Project Compability?

**Comment by pamidur** [comment]
Hi,
It is compatible with .NET Core. There is a branch - mono-cecil-10-migration, it contains working code for mono-cecil-10 which supports .NET Core. However mono-cecil-10 is still in beta so there is no ready-for-something build avaliable. You can build it on your own.

**Comment by drony** [comment]
I'm traying for s couple hours, unfortunately I could not work :( any sample?

**Comment by Dreamescaper** [comment]
@pamidur
Would it be possible to create a pre-release nuget package from that branch?

**Comment by pamidur** [comment]
@Dreamescaper I'm working on that

**Comment by drony** [comment]
any news soon?

**Comment by pamidur** [comment]
Unfortunately mono cecil is in the same state - it is beta 7 release from on Nov 3, 2017. So I guess will release pre-release package on nuget.

**Comment by drony** [comment]
also i think Fody use beta version of cecil.

**Comment by kingreatwill** [comment]
Don't give up. We are all looking forward to it.

**Comment by pamidur** [comment]
Guys, please check https://github.com/pamidur/aspect-injector/releases/tag/1.5.0-beta and report shell you found any bugs.
