### ISSUE TITLE
Aspect should not inject into itself.

### ISSUE THREAD

**Issue by pamidur** [pamidur/aspect-injector#68]
When aspect is defined in the same assembly where injection happens. It is possible for aspect to inject into itself.

**Comment by pamidur** [comment]
See #64 For details

**Comment by Dreamescaper** [comment]
How do you think, should it be injected into other aspects?
If yes - I suppose it will lead to same issue, but with two aspects

**Comment by Dreamescaper** [comment]
Personally I can't imagine situation where I'd need to inject something into aspects.

I'm just trying to come up with best behavior for that.

If we prevent injection into aspects in all cases (probably, the easiest way) - what should be done with explicit attributes on aspects? 
Throw error at build time? Or silently ignore?

**Comment by pamidur** [comment]
Silently ignore - the easiest way. But I'd say ignore and throw warning at build time

**Comment by YuriyIvon** [comment]
Added quick fix in e3f6a74b41c2372077231f41f361e4f9c4ea209a

**Comment by pamidur** [comment]
release in 1.5.0-beta
