### ISSUE TITLE
Create Roslyn Analyzer 

### ISSUE THREAD

**Issue by pamidur** [pamidur/aspect-injector#72]
subj

**Comment by admedina** [comment]
I am loving Aspect Injector and I would really like to say thank you for building it!  Has there been anymore work done to support this feature?

**Comment by pamidur** [comment]
Hi, thank for your feedback. It is really motivating!
As to Roslyn Analyzer - it is partially done. It supports c# only and performs code checks in desing time. Fix suggestions and vb.net support are in plans.

**Comment by admedina** [comment]
This might come from a lack of understanding the correct terminology but is there a way to create analyzers to enforce checks such as `[NotNull] string argument`? Or would that be outside the goal of the analyzers you're working on?

**Comment by pamidur** [comment]
Oh, I guess I got your idea. Such checks can be implemented in Roslyn for design time and in AspectInjector for runtime. Yes, you already can implement [NotNull] counterpart for runtime in AspectInjector.

As to this particular issue - this is about enforcement of correct parameters in advice methods and overall aspect implementation.

If you need any help or have any ideas for new features please feel free to create new issues!

**Comment by pamidur** [comment]
Will close this as the basic feature was done for c# and vb.net is rather dead
