### ISSUE TITLE
Attribute Multicasting

### ISSUE THREAD

**Issue by ocherniavskyi** [pamidur/aspect-injector#78]
Hi, do you have any plans for Attribute Multicasting e.g. https://doc.postsharp.net/multicast-conceptual. From my side i desperately need a way how to apply Injection for methods that already marked with attribute to extend unit test framework functionality

**Comment by pamidur** [comment]
Hi, this is the case from very beginning, if I understood Multicasting correctly.
For instance you can apply attribute to whole assembly, and advice will be injected into every single class/nestedclass/method

**Comment by ocherniavskyi** [comment]
Im onle need to inject into methods which suplied with [TestCase] attribute for instance - and not for method without this atrribute, is it possible?

**Comment by pamidur** [comment]
I got your point. No, unfortunately there is no (yet) filter by existing attribute. However if you're ok with little magic in runtime, you can do this:

```c#
using AspectInjector.Broker;
using System;
using System.Reflection;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var mytestClass = new MyTestClass();
            mytestClass.NoAttribute(); //not me            
            mytestClass.WithAttribute(); //Gotcha: catch me!
        }
    }

    internal class MyMarkerAttribute : Attribute { }

    [MySelectiveAspect]
    internal class MyTestClass
    {
        public void NoAttribute()
        {
            Console.WriteLine("not me");
        }

        [MyMarker]
        public void WithAttribute()
        {
            Console.WriteLine("catch me!");
        }
    }

    [Aspect(Scope.Global)]
    [Injection(typeof(MySelectiveAspect))]
    internal class MySelectiveAspect : Attribute
    {
        [Advice(Kind.Before, Targets = Target.Public | Target.Method)]
        public void Before([Argument(Source.Method)]MethodBase method)
        {
            if (method.GetCustomAttribute<MyMarkerAttribute>() != null)
                Console.Write("Gotcha: ");
        }
    }
}

```
Note: this in fact inject into all public methods, but executes code selectively.
Note2: the snippet is for v2.0.0-beta1, but can be adjusted for earlier versions

**Comment by ocherniavskyi** [comment]
Thank you, i will try, but filtering or targeting would be a grate feature

**Comment by ocherniavskyi** [comment]
Can i apply MySelectiveAspect to all classes in assembly in one place?

**Comment by pamidur** [comment]
Yes, put somewhere [assembly: MySelectiveAspect]

The filter is there only by access, member and scope now. In near future Im gonna add filter by name with wildcards. I'll take at filtering by attribute afterwards

**Comment by ocherniavskyi** [comment]
Thanks a lot for your grate work.

**Comment by pamidur** [comment]
Create #89 to track advanced filtering
Feel free to reopen if needed.
