### ISSUE TITLE
StackOverflowException when applying injection on assembly and running Nunit test

### ISSUE THREAD

**Issue by ocherniavskyi** [pamidur/aspect-injector#80]
Visual Studio 2017 Pro 15.9.1

Failed to run nunit tests due to StackOverflowException when applying injection to whole assembly. But it successfully runs when injection applies to class.

[AspectIssue.zip](https://github.com/pamidur/aspect-injector/files/2722417/AspectIssue.zip)

**Comment by pamidur** [comment]
Thanks, the issue is there. We still injecting aspects into aspects. This seem like regression. Will be fixed soon

**Comment by pamidur** [comment]
fixed in 2.0.1
