### ISSUE TITLE
AspectInjector doesn't work correcly with generic methods.

### ISSUE THREAD

**Issue by OlegYanushkevich** [pamidur/aspect-injector#85]
When I am using Advice with Kind.Around for generic method, I'm getting System.Security.VerificationException.
![capt](https://user-images.githubusercontent.com/28996736/52524052-9a388000-2ca9-11e9-83a0-53afb5827dbd.PNG)
Environment: Windows 10, .net core 2.2.103

**Comment by pamidur** [comment]
Thanks for the report. Would you mind providing an example of the generic method and its constraints?

**Comment by OlegYanushkevich** [comment]
@pamidur, no problem. You will see method [here](https://github.com/OlegYanushkevich/QAutomation/blob/master/QAutomation.Selenium/ElementFinderService.cs) on 26 line. And execution example [here](https://github.com/OlegYanushkevich/QAutomation/blob/master/Test/Program.cs) on 46 line.

**Comment by OlegYanushkevich** [comment]
You can see aspect definition [here](https://github.com/OlegYanushkevich/QAutomation/blob/master/QAutomation.AspectInjector/Logged.cs). I use AspectInjector 2.0.5.

**Comment by pamidur** [comment]
Please check out 2.0.6 . Should be fixed now

**Comment by OlegYanushkevich** [comment]
Yes, it's working now.Great. Thanks for your good job.
