### ISSUE TITLE
Why i have so many DLLs file in Debug folder?

### ISSUE THREAD

**Issue by prixodkooleg0** [pamidur/aspect-injector#86]
It is super project, Thank you. I used version 1.0.1 was ok. Now i try lastest version and have all framework dlls in debug folder. How can i fix this? i am using MVS2017.

**Comment by pamidur** [comment]
I suspect you're not using TFM that directly supports netstandard2.0. Can you me  please what framework you target?

**Comment by pamidur** [comment]
net461
![image](https://user-images.githubusercontent.com/4095184/54869545-de3b9c00-4da2-11e9-98ce-ca665a5a68bd.png)
net471
![image](https://user-images.githubusercontent.com/4095184/54869556-fb706a80-4da2-11e9-927c-e52a3f773985.png)

**Comment by pamidur** [comment]
https://stackoverflow.com/questions/47184230/large-number-of-assemblies-in-net461-output-folder-when-building-net-framework

**Comment by prixodkooleg0** [comment]
Using framework 4.7.2 helps. Thank you very much. And program steel donot need AspectInjector.Broker.dll after build?( i must copy only .exe file?)

**Comment by pamidur** [comment]
This the whole point here -> AspectInjector.Broker.dll is now required.
This is done for better compatibility, for ease reusing aspects into other assemblies and for other features in future. The drawback is that you need this dll to be alongside your exe.

**Comment by prixodkooleg0** [comment]
I am set donot copy to AspectInjector.Broker.dll and then copy exe file to another folder and it is works.

**Comment by pamidur** [comment]
Well no problem with that. I'm glad it works for you, just be aware it works until you try to get custom attributes on your classes.

**Comment by pamidur** [comment]
Closed. Feel free to reopen if needed.
