### ISSUE TITLE
I want to know how to trigger dynamic injection of IL when I compile an assembly.

### ISSUE THREAD

**Issue by tzm1119** [pamidur/aspect-injector#87]
I just see this logs.I want to know why I press F5 in vs,this can be exectued

1>  AspectInjector: Started for AspectInjector.SampleApps.NotifyPropertyChanged.exe
1>  AspectInjector: Assembly has been read.
1>  AspectInjector: Found 1 aspects
1>  AspectInjector: Found 4 injections
1>  AspectInjector: Processing aspects...
1>  AspectInjector: Processing injections...
1>  AspectInjector: Executing AdviceInlineWeaver...
1>  AspectInjector: Executing AdviceStateMachineWeaver...

Thanks a lot

**Comment by pamidur** [comment]
If I understand your question correctly, you want to know how we're triggering injections. 
We use nuget feature which allows import target files from nuget package. Then using this target file we execute aspectinjector with msbuild write after compilation.
You can see it here https://github.com/pamidur/aspect-injector/blob/master/nuget/build/AspectInjector.targets

**Comment by tzm1119** [comment]
I get it. Thanks

**Comment by tzm1119** [comment]
I have a suggestion.Just like below. it is your example.
I do not want to write [Notify] anywhere.
I just want to write a rule, just like I want all Class in my project which Name endwith "ViewModel",I want to add [Notify] to its all properties. 
I think is more convenient.

public class AppViewModel
    {
        [Notify]
        public string FirstName { get; set; }

        [Notify(NotifyAlso = nameof(Fullname))]
        public string LastName { get; set; }

        public string Fullname => $"{FirstName} {LastName}";

    }

**Comment by pamidur** [comment]
You already can apply your [Notify] to a class or other whole assembly [assembly:Notify].
The name filter is under development, and will be available in future versions

**Comment by pamidur** [comment]
Created #89 . So we can track naming filter feature.
Feel free to reopen if needed.
