### ISSUE TITLE
Compile error in VS 2017

### ISSUE THREAD

**Issue by twzhangyang** [pamidur/aspect-injector#88]
Hi  @pamidur ,

The project targeted to netcoreapp2.2, Some colleagues can compile successful but two of them can not. Got such compile errors in VS2017:
The version of AspectInjector  is 2.0.2, Do you have any suggestions for this error?
Thanks,
Yang

<img width="1426" alt=":Users:yrzhang:Downloads:image (3)" src="https://user-images.githubusercontent.com/22952792/55400524-b3aac980-5580-11e9-9fbd-0c356552f997.png">

![image (4)](https://user-images.githubusercontent.com/22952792/55400606-e654c200-5580-11e9-8b8c-ef0ad996a55b.png)

**Comment by pamidur** [comment]
Hi, 
Seems like incorrect referencing aspectinjector. Try to unreferrnce it and add it from Nuget again. 

It might help if you could send a .csproj file

**Comment by jaanifly** [comment]
Hi @pamidur,

This is my .csproj file
![image](https://user-images.githubusercontent.com/6056270/55449546-83097500-55fe-11e9-8782-26e35e5be17d.png)
Cheers
Jaani

**Comment by pamidur** [comment]
Hi Jaani,

I've found what's wrong. 
```xml
    <PackageReference Include="AspectInjector" Version="2.0.6" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; contentfiles; analyzers; native</IncludeAssets>
    </PackageReference>
```

Aspect Injector used to mark it's assets as private in previous versions. But not anymore. I don't know if you intentionally set _PrivateAssets_ and _IncludeAssests_ or it is left after upgrade. So the solution is either remove  _PrivateAssets_ and _IncludeAssests_ lines:
```xml
    <PackageReference Include="AspectInjector" Version="2.0.6" >
    </PackageReference>
```
or (if you set those lines intentionally) add **compile** to _IncludeAssests_
```xml
    <PackageReference Include="AspectInjector" Version="2.0.6" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; contentfiles; analyzers; native; compile</IncludeAssets>
    </PackageReference>
```


Btw, if you remove AspectInjector completely and add it again you'll have it like this
```xml
<PackageReference Include="AspectInjector" Version="2.0.6" />
```

**Comment by pamidur** [comment]
Did it help?

**Comment by jaanifly** [comment]
Hi @pamidur, I tried removing the include assets, still no help.

**Comment by pamidur** [comment]
Have tried to add "**compile**" to the list?

**Comment by twzhangyang** [comment]
Hi @pamidur 

Thanks for your patience. I try to compile current project in several machines and turns out it's all build successful. 
Right now @jaanifly is only one who can not compile this project in his machine. he will re-install VS in his machine. 
We still don't know why his VS will report this compile error but let's waiting his result after re-installed VS. 

Thanks,
Yang

**Comment by pamidur** [comment]
Try re clone your repo to another directory. Optionally go ahead and remove all bon and obj folders. And also try remove c\users\<user>\.nuget

**Comment by pamidur** [comment]
Any luck with this issue?

**Comment by jaanifly** [comment]
1. Deleted bin and obj folders
2. Re-cloned repo
3. Reinstalled VS
4. Reinstalled dotnet
5. Removed .nuget packages

Still no help @pamidur. Looks weird!

**Comment by jaanifly** [comment]
Hi @pamidur 
Updated my version to 2.1.1 and it works! 
Looks like a compatibility issue earlier I was using 2.0.1 with dotnet core 2.2.103.
And thanks much for your help.
