### ISSUE TITLE
AspectInjector exec reaches cmd char limit

### ISSUE THREAD

**Issue by 564064202** [pamidur/aspect-injector#90]
it doesn't work on asp.net core webapi,grpc (2019)

**Comment by pamidur** [comment]
Hi, 
Would you mind to provide an additional info like project sample or build log?

**Comment by 564064202** [comment]
[http://97.64.126.29:3000/AsyncAop.7z](url)
you can also create the project by yourselef .

**Comment by 564064202** [comment]
please tell us the reason why it didn't work

**Comment by pamidur** [comment]
I'm afraid your link doesn't work. Could you please reupload it somewhere or just post you *csproj and *cs files here.

But the name of the file implies you try to wrap around async methods.You may want to check this issue #77

**Comment by 564064202** [comment]
it's ok now.

**Comment by 564064202** [comment]
please download it,and then I will shutdown it

**Comment by pamidur** [comment]
Ok, thanks, I found the issue. It seems that aspnetcore 3.0 has so many dependencies that we simply reach the limit for command execution while passing all those references. I'll be working on it.

**Comment by pamidur** [comment]
check out version 2.1.0 should work fine now

**Comment by 564064202** [comment]
thanks
