### ISSUE TITLE
can we use it without visual studio?

### ISSUE THREAD

**Issue by 564064202** [pamidur/aspect-injector#91]
can we use it without visual studio?

**Comment by 564064202** [comment]
hello?

**Comment by pamidur** [comment]
Hi, yes you can. Visual studio is not necessary.
You can build your project from command line using Msbuild. Even more aspectinjector is mere an executable, so you can trigger injections when you want, however this last scenario is not officially supported.

If describe your need in details, I might come up with another suggestion.

**Comment by 564064202** [comment]
We have a scenario:
 our program will   generate a dotnet project (which  contains aspectinjector )  automaticlly,
and then our program will build the project  by dotnet cil,how we can do it?

**Comment by pamidur** [comment]
"dotnet build" definitely works fine aspectinjector

**Comment by 564064202** [comment]
perfect! thank you every much!

**Comment by pamidur** [comment]
Closed, feel free to reopen if needed
