### ISSUE TITLE
Compilation error - failed to resolve assembly

### ISSUE THREAD

**Issue by saqw3r** [pamidur/aspect-injector#92]
After installing Nuget packages and building the project I've got next sequence of compilation errors: 

Error - Aspect Injector processing has failed. See other errors.
Error - Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by pamidur** [comment]
Hi,
Thanks for report. What the version of aspectinjector you're using?

**Comment by saqw3r** [comment]
Hey, I can only give you the version of AspectInjector: "AspectInjector.Broker, Version=1.0.1.0, Culture=neutral, PublicKeyToken=a29e12442a3d3609, processorArchitecture=MSIL". Unfortunately, the project is under NDA

**Comment by pamidur** [comment]
Unfortunately, this version is quite outdated. Try using latest one (2.1.0 at the moment) it has majority of the issues fixed and has better performance

**Comment by saqw3r** [comment]
Unfortunately, this version doesn't support .net 4.5.2  - and it's a requirement that I cannot change on my project.

**Comment by pamidur** [comment]
I've had a look at v 1.0.1. I couldn't find why it is hapenning. I could guess and ask you to try to reference this library in your project directly.

It might also help if you set your build log to diagnostic and look for lines like 
```
9>  Task "Exec"
9>  Task Parameter:Command=dotnet  {...} AspectInjector.dll {there should go references, System.Web.WebPages should be one of them}
```
and drop them here


If you ever consider to move to net461 - it supports netstandard 2.0

**Comment by saqw3r** [comment]
The only build log, related to this error, I found:
10>EXEC : error : Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Web.WebPages, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
10>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
10>     at AspectInjector.Core.Utils.KnownReferencesAssemblyResolver.LookupAssembly(AssemblyNameReference name, ReaderParameters parameters)
10>     at AspectInjector.Core.Utils.CachedAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
10>     at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name)
10>     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
10>     at Mono.Cecil.TypeReference.Resolve()
10>     at AspectInjector.Core.Extensions.TypeReferenceExtensions.BelongsToAssembly(TypeReference tr, Byte[] publicKey)
10>     at AspectInjector.Core.Services.Janitor.CheckInstructionReferencesBroker(Instruction instruction)
10>     at System.Collections.Generic.List`1.ForEach(Action`1 action)
10>     at AspectInjector.Core.Services.Janitor.CheckMethodBodyReferencesBroker(MethodBody methodBody)
10>     at AspectInjector.Core.Services.Janitor.CheckMethodReferencesBroker(MethodDefinition method)
10>     at System.Collections.Generic.List`1.ForEach(Action`1 action)
10>     at AspectInjector.Core.Services.Janitor.CheckTypeReferencesBroker(TypeDefinition type)
10>     at System.Collections.Generic.List`1.ForEach(Action`1 action)
10>     at AspectInjector.Core.Services.Janitor.CleanupModule(ModuleDefinition module)
10>     at AspectInjector.Core.Services.Janitor.Cleanup(AssemblyDefinition assembly)
10>     at AspectInjector.Core.Processor.ProcessAssembly(AssemblyDefinition assembly)
10>     at AspectInjector.Core.Processor.Process(String assemblyFile, IAssemblyResolver resolver)
10>     at AspectInjector.Commands.ProcessCommand.Execute(IReadOnlyList`1 args)
10>AspectInjector : error ASI0001: Aspect Injector processing has failed. See other errors.

**Comment by saqw3r** [comment]
"If you ever consider to move to net461 - it supports netstandard 2.0" - no, it's not an option

**Comment by saqw3r** [comment]
[BuildLogs.txt](https://github.com/pamidur/aspect-injector/files/3108323/BuildLogs.txt)

**Comment by pamidur** [comment]
Back in the days of v1, AspectInjector used to go through your code remove any dependency to AspectInjector.Broker. It seems like for some reason when it tries to figure which assembly particular reference belongs to, the resolver could not find **System.Web.WebPages** dll. Dll resolution especially for MVC might be tricky. Thus I think that if you explicitly reference **System.Web.WebPages, Version=3.0.0.0** this could fix the issue.

I also looked into the newer code, where the approach is different (v2.0), and it seems like the gap between two is quite big, so I don't think it is possible to make a backport in reasonable amount of time.

Last resort :) is  - you can compile your own version of AspectInjector 1.0.1. Where you can disable call to __janitor.Cleanup()_ in **/src/AspectInjector.Core/Processor.cs:102**. The only downside would be that you have to keep AspectInjector.Broker.dll in your bin - make sure you set it to copylocal=true

**Comment by pamidur** [comment]
Would you mind to check what the exact file name of "E:\projectRootFolder\packages\Microsoft.AspNet.Webpages.3.2.3\lib\net45\System.Web.Webpages.dll" ?

**Comment by pamidur** [comment]
idk if it helps I've made dll search less strict and created prerelease version 
https://www.nuget.org/packages/AspectInjector/1.0.2-pre

let me know if it helps

**Comment by saqw3r** [comment]
> 
> 
> idk if it helps I've made dll search less strict and created prerelease version
> https://www.nuget.org/packages/AspectInjector/1.0.2-pre
> 
> let me know if it helps

Yeah, the compilation error at least has been thrown away!

**Comment by saqw3r** [comment]
And here the list of files from "E:\projectRootFolder\packages\Microsoft.AspNet.Webpages.3.2.3\lib\net45\" :
![изображение](https://user-images.githubusercontent.com/8653893/56603195-d26f0f80-65c4-11e9-981f-a97d2c4d894a.png)

**Comment by pamidur** [comment]
Let me know if it works as expected, So I make a proper release for both v1 and v2

**Comment by saqw3r** [comment]
Yeah, although there where some troubles with pre-release prefix, but I found workaround and it seems ok.

**Comment by pamidur** [comment]
I've created stable release https://www.nuget.org/packages/AspectInjector/1.0.2
Please fill free to reopen if needed

**Comment by Peterdaemonx** [comment]
After deploy solución in tests enviroment I've got next sequence of compilation errors:
Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

**Comment by pamidur** [comment]
Thanks for report.

Could please specify AspectInjector version you're using, what framework you're targeting and how you build your app?
