### ISSUE TITLE
Investigave attributes injection (same way as interface injections)

### ISSUE THREAD

**Issue by introspection3** [pamidur/aspect-injector#93]
sir,how to add an attribute to a class

**Comment by pamidur** [comment]
Hi,
Can you please elaborate more on this?

**Comment by 564064202** [comment]
We have an error when we migrate asp.net webapi to asp.net core (we have to use swagger core ,
but swagger core need every action explicit HttpMethod binding)

Ambiguous HTTP method for action - Permission.Service.Controllers.RoleController.GetRoleConfigValue (Permission.Service). Actions require an explicit HttpMethod binding for Swagger 2.0

**Comment by pamidur** [comment]
Ok, I guess I understand. So you want an api that allows adding attributes to a class(or member) after
compilation. Is that correct?

**Comment by 564064202** [comment]
yes

**Comment by pamidur** [comment]
This is an interesting idea. We will investigate it and may be implement in future. For now, unfortunately , aspect injector cannot do it

**Comment by 564064202** [comment]
ok,thanks all the same

**Comment by pamidur** [comment]
Will not be implemented. 
Same can be achieved by using base classes with inherited attributes
