### ISSUE TITLE
Aspect is injected into local methods

### ISSUE THREAD

**Issue by marektoman** [pamidur/aspect-injector#95]
When I have a lambda expression inside a method, the aspect is injected into both:

```csharp
[Injection(typeof(Trace))]
[Aspect(Scope.PerInstance)]
public class Trace : Attribute
{
    static int level = 0;

    [Advice(Kind.Before, Targets = Target.Method)]
    public void HandleBefore([Argument(Source.Metadata)] MethodBase method)
    {
        Console.WriteLine("{0}begin {1}", "".PadRight(level * 4), method);
        level++;
    }

    [Advice(Kind.After, Targets = Target.Method)]
    public void HandleAfter([Argument(Source.Metadata)] MethodBase method)
    {
        level--;
        Console.WriteLine("{0}end {1}", "".PadRight(level * 4), method);
    }
}

[Trace]
public class TraceConsumer
{
    public void Method()
    {
        int[] a = { 0, 1 };
        a.Single(x => x == 1);
    }
}
```

Calling `Method()` results in:
```
begin Void Method()
    begin Boolean <Method>b__0_0(Int32)
    end Boolean <Method>b__0_0(Int32)
    begin Boolean <Method>b__0_0(Int32)
    end Boolean <Method>b__0_0(Int32)
end Void Method()
```

Is there a way to avoid injection into local methods or is there a workaround (e.g. is the `<Method>` naming unique to local methods)?

**Comment by pamidur** [comment]
Hi, thank you for report. This is definitely an issue. I guest we shouldn't inject into anonymous methods. I'll be working on it. 
Until then you could mark with [Trace] only your Method () instead of whole class

**Comment by marektoman** [comment]
@pamidur  In case you are deciding what the default behavior should be, I propose only injecting into member methods, so both anonymous functions and local named functions (c# 7 feature) should not be affected. I usually rewrite/extract anonymous functions as local functions, so there's no difference in my mind.

BTW I haven't tested how class level anonymous functions like delegate fields behave.

**Comment by marektoman** [comment]
This issue also extends to async/await methods:
```csharp
public async Task AsyncMethod()
{
    Console.WriteLine("AsyncMethod 1");
    await Task.Delay(1);
    Console.WriteLine("AsyncMethod 2");
    await Task.Delay(1);
    Console.WriteLine("AsyncMethod 3");
}
```
```
begin AsyncMethod
    begin MoveNext
AsyncMethod 1
    end MoveNext
    begin MoveNext
AsyncMethod 2
    end MoveNext
    begin MoveNext
AsyncMethod 3
    end AsyncMethod
end MoveNext
```

**Comment by marektoman** [comment]
I currently use the following workaround, which avoids all the cases mentioned above:
```csharp
[Advice(Kind.Before, Targets = Target.Method)]
public void HandleBefore(
    [Argument(Source.Type)] Type owner,
    [Argument(Source.Name)] string methodName)
{
    if (owner.Name.StartsWith('<') || methodName.StartsWith('<')) return;
    // TODO
}
```

**Comment by marektoman** [comment]
One last thing, just in case you consider disabling injection into non-member functions completely, one scenario where I would really like to opt-in for this at the class level is argument validation.

**Comment by pamidur** [comment]
FYI, Although this works, the compiler generated method names are totally up to compiler itself. As far as I know all compilers (even mono) use the same naming schema as of now, but it doesn't it will not change in future.

**Comment by pamidur** [comment]
Would you mind to provide an example of such scenario where you might want to inject into anonymous methods?

**Comment by marektoman** [comment]
Thanks for the clarification.

I've [this](https://gist.github.com/marektoman/e1a3579afed5e88d87793db9ce25d3f1) aspect (WIP), which validates all arguments. It checks if a parameter is decorated with an additional attribute and if it isn't, it validates the argument for the default case. E.g. for strings, this may be not empty (or not white space). Part of the point is that it works just by decorating the class and doesn't silently fail if I forgot to decorate a method or parameter. This is useful in lambda functions in the same way.

**Comment by pamidur** [comment]
I see your point. Thank you.
Although this is very valid point, I'm quite sure that injections should be applied to members  that developer "can see", sorry such explanation :) I mean that I'd rather inject only into visible members in order not to confuse developer.
For instance in your scenario the issue is that anonymous method are often used with linq(-to-objects) operating on lists that may contain null values. The nature of linq is the inverted control (laziness) - you pass the method and the system decides when, how many times if at all to execute mentioned method. Thus we might end up with hidden issues. What do you think?

**Comment by pamidur** [comment]
For instance I'm really afraid of performance loss in case any method contains any lambda on list with thousand elements

**Comment by marektoman** [comment]
I completely agree, the default behavior should be that it only injects into member methods.

On top of that, if I'm able to opt in by setting one of the attributes (Advice, Aspect, or Injection) to explicitly say "inject everywhere", that would be really useful. The full behavior can be described in the description of that attribute property so there's no ambiguity.

**Comment by marektoman** [comment]
Regarding the LINQ laziness, if I pass a member method I have the same problem, and this becomes the required scenario anyway if I cannot enable injection into lambda functions and still need injection.

**Comment by pamidur** [comment]
I'll be releasing new version with propagation control soon

**Comment by marektoman** [comment]
Thanks for the update.

Big kudos for the project, BTW.

**Comment by pamidur** [comment]
I've temporarily unlisted the update, because debugging was broken for Around advices. I'm working on proper update with new propagation control feature.

**Comment by pamidur** [comment]
I encourage you to check out 2.2.1 version. It has [Injection] attribute with additional properties that control propagation.
